version: "3.9"

services:
  atakentfrontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: atakentfrontend
    ports:
      - "3000:80"
    networks:
      - atakentfrontendnetwork
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/certs
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - atakentfrontendnetwork

networks:
  atakentfrontendnetwork:
    driver: bridge
